// Test exported HTML handlers without claiming a real-browser layout test.
const fs = require('node:fs'), vm = require('node:vm'), assert = require('node:assert/strict');
const html = fs.readFileSync(process.argv[2], 'utf8');
const report = JSON.parse(fs.readFileSync(process.argv[2].replace(/report\.html$/, 'report.json'), 'utf8'));
const decode = s => s.replace(/&quot;/g,'"').replace(/&#x27;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
const nodes = {}, policies = [];
for (const match of html.matchAll(/\bid="([^"]+)"/g)) nodes[match[1]] = {value:'',checked:false,textContent:'',addEventListener(name, fn){this[name]=fn;}};
for (const match of html.matchAll(/<input\b[^>]*data-policy="([^"]+)"[^>]*value="([^"]*)"[^>]*>/g)) policies.push({dataset:{policy:match[1]}, value:decode(match[2])});
for (const [id, value] of Object.entries({'policy-min':report.policy.min_monthly_salary,'policy-max':report.policy.max_monthly_salary??'','policy-score':report.policy.min_score,'policy-salary-mode':report.policy.salary_mode,'policy-unknown':report.policy.unknown_policy})) nodes[id].value=String(value);
for (const s of report.suggestions) if (nodes['text-'+s.id]) nodes['text-'+s.id].value=s.after;
nodes['review-data'].textContent = html.match(/<script type="application\/json" id="review-data">([\s\S]*?)<\/script>/)[1];
let lastBlob, downloads=0;
const document = {getElementById:id=>nodes[id],querySelectorAll:()=>policies,createElement:()=>({click(){downloads++;}})};
vm.runInNewContext(html.match(/<script>([\s\S]*?)<\/script>/)[1], {document, Blob:class{constructor(parts){this.text=parts.join('');}}, URL:{createObjectURL(blob){lastBlob=blob;return 'blob:test';},revokeObjectURL(){}},setTimeout:fn=>fn()});
nodes['download-policy'].click();
assert.equal(JSON.parse(lastBlob.text).min_monthly_salary, report.policy.min_monthly_salary);
assert.deepEqual(JSON.parse(lastBlob.text).cities, report.policy.cities);
const prior=downloads;
nodes['policy-min'].value='50000';nodes['policy-max'].value='30000';nodes['download-policy'].click();
assert.equal(downloads,prior);
assert.match(nodes['policy-message'].textContent,/检查/);
nodes.download.click();assert.match(nodes.message.textContent,/至少/);
const suggestion=report.suggestions.find(s=>s.kind==='rewrite');
nodes['action-'+suggestion.id].value='accept';nodes.download.click();assert.match(nodes.message.textContent,/勾选/);
nodes['confirm-'+suggestion.id].checked=true;nodes.download.click();
const decisions=JSON.parse(lastBlob.text);
assert.equal(decisions.cycle_id,report.id);assert.equal(decisions.decisions[0].text,suggestion.after);
assert.equal(decisions.decisions[0].confirmed,true);
console.log('Review handlers: settings export, invalid ranges, confirmation, decision export passed.');
